[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fa_assist"
version = "0.1.0"
description = "Developer utilities and productivity tools for FastAPI"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

dependencies = [
    "typer",
    "aiofiles",
    "aiomysql",
    "click",
    "cryptography",
    "cython",
    "defusedxml",
    "dotenv",
    "fastapi",
    "google-auth",
    "google-cloud",
    "google-cloud-bigquery[pandas]",
    "jinja2",
    "openpyxl",
    "orjson",
    "pandas",
    "numpy",
    "pydantic[email]",
    "pydantic-settings",
    "pyjwt",
    "python-dotenv",
    "python-multipart",
    "setuptools",
    "tortoise",
    "tortoise-orm[aiomysql]",
    "uvicorn",
    "uvicorn-worker",
    "xlsxwriter",
    "aerich[toml]",
]
[project.scripts]
fa_assist = "fa_assist.cli:main"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "httpx",
    "ruff",
    "typer"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
